# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Smart Data
tagline:          'Smart Data Integration for Urban Modeling'
description:      'A project funded by <a href="http://otrec.us/nitc" target="_blank">NITC</a>'
url:              http://cities.github.io/smartdata

author:
  name:           'Liming Wang'
  url:            'http://web.pdx.edu/~limwang'

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/cities/smartdata
